# Generated by Django 3.2 on 2021-04-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210409_1709'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reservationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.reservation'),
        ),
    ]
