# Generated by Django 3.2 on 2021-04-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_reservationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='email',
        ),
    ]
