# Generated by Django 3.2 on 2021-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_room_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
