# Generated by Django 3.1.4 on 2021-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=11)),
                ('password', models.TextField(max_length=10)),
            ],
        ),
    ]
