# Generated by Django 3.2 on 2021-04-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0002_customer_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
