# Generated by Django 3.2 on 2021-04-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_login', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=11)),
                ('password', models.TextField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
