# Generated by Django 3.2 on 2021-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('roomtype', models.TextField(max_length=25)),
                ('rooms', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
