# Generated by Django 3.1.4 on 2021-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('roomtype', models.TextField()),
                ('rooms', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
