# Generated by Django 3.1.4 on 2021-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='roomtype',
            field=models.TextField(max_length=15),
        ),
    ]
