# Generated by Django 3.2 on 2021-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roomtype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'single'), (2, 'double'), (3, 'suite'), (4, 'luxury')]),
        ),
    ]
