# Generated by Django 3.1.4 on 2021-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210405_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
