# Generated by Django 3.1.4 on 2021-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210406_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateField(),
        ),
    ]
