# Generated by Django 3.2 on 2021-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210409_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_time',
            field=models.CharField(max_length=10),
        ),
    ]
